### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by anandarivu** [diasdavid/webrtc-explorer#20]
Hi @daviddias ,

Is the code base production ready? Also i could not find a way to support media calls (audio, video). Is repo not meant for media calls?

Thanks in advance

**Comment by daviddias** [comment]
Hi @anandarivu! What are you trying to build? This code was built for Research for my M.Sc thesis and it met its purpose (transferring data and computation over an overlay network), i twas not design for calls. Read more about it at:

- http://daviddias.me/blog/webrtc-explorer-2-0-0-alpha-release/
- http://daviddias.me/blog/enter-webrtc-explorer/
-  http://daviddias.me/blog/webrtc-ring/

**Comment by daviddias** [comment]
Closing this issue for now. Let me know if any other questions arise :)
